data/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('data.views',
    url(r'^autocomplete_course/', 'autocomplete_course'),
    url(r'^autocomplete_specialization/', 'autocomplete_specialization'),
    url(r'^autocomplete_skill/', 'autocomplete_skill'),
)

schoolax/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover


admin.autodiscover()
dajaxice_autodiscover()

handler403 = 'core.views.error_403'
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'views.home', name='home'),
    # url(r'^Minerva/', include('foo.urls')),
    # Import URLs
    url(r'', include('bulletin.urls')),
    url(r'', include('account.urls')),
    url(r'', include('homeroom.urls')),
    url(r'', include('course.urls')),
    url(r'', include('portfolio.urls')),
    url(r'', include('backstage.urls')),
    url(r'', include('data.urls')),
    # Admin URLs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # AJAX URLs
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls'))
)

# Static File URLs
urlpatterns += staticfiles_urlpatterns()

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
# from django.core.exceptions import ValidationError
from core.models import Institute, ProvinceState
from core.constants import (DEGREE, GRADE,
    GRADE_MAX, GRADE_MIN, GRADE_STEP)
from core.utilities import generate_username


@receiver(pre_save, sender=User)
def user_pre_save(sender, **kwargs):

    ''' Ensures Django User's e-mail is unique '''

    email = kwargs['instance'].email
    username = kwargs['instance'].username
    if sender.objects.filter(email=email).exclude(username=username).count() and email:
        # raise ValidationError('User email needs to be unique')
        pass


class Profile(models.Model):

    ''' Extends the Django User '''

    user = models.OneToOneField(User)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    tagline = models.TextField(null=True, blank=True)
    institute = models.ForeignKey(Institute, null=True, blank=True)
    degree = models.CharField(max_length=2, choices=DEGREE, null=True, blank=True)
    grade = models.IntegerField(choices=GRADE, default=0)
    grade_gauge = models.IntegerField(default=0)
    influence = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s' % (self.user.get_full_name())

    @staticmethod
    def register_user(email, password, first_name, last_name, institute):
        user = User()
        user.username = generate_username()
        user.email = email
        user.set_password(password)
        user.first_name = first_name
        user.last_name = last_name
        user.is_active = True
        user.save()
        profile = Profile()
        profile.user = user
        profile.institute = institute
        profile.save()

    def increment_grade(self, delta):
        self.grade_gauge += delta
        if self.grade_gauge >= GRADE_STEP:
            self.grade += 1
            self.grade_gauge -= GRADE_STEP
            if self.grade >= GRADE_MAX:
                self.grade = GRADE_MAX
                self.grade_gauge = 100
        elif self.grade_gauge <= -GRADE_STEP:
            self.grade -= 1
            self.grade_gauge += GRADE_STEP
            if self.grade <= GRADE_MIN:
                self.grade = GRADE_MIN
                self.grade_gauge = -100
        self.save()

    class Meta:
        db_table = 'mva_profile'


class Contact(models.Model):

    label = models.CharField(max_length=100)
    user = models.ForeignKey(User)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    province_state = models.ForeignKey(ProvinceState, verbose_name='province/state')
    telephone = models.CharField(max_length=100, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True, verbose_name='e-mail')

    def __unicode__(self):
        return self.label

    class Meta:
        db_table = 'mva_contact'

core/models.py
from django.db import models
from django.contrib.auth.models import User
from core.abstract_models import SentContent
from core.constants import INSTITUTE_CATEGORY, SKILL_RATING


class Country(models.Model):

    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'mva_country'
        verbose_name_plural = 'countries'


class ProvinceState(models.Model):

    name = models.CharField(max_length=100)
    abbrev = models.CharField(max_length=5, verbose_name='abbreviation', null=True, blank=True)
    country = models.ForeignKey(Country)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'mva_province_state'
        verbose_name = 'province/state'
        verbose_name_plural = 'provinces/states'


class Institute(models.Model):

    name = models.CharField(max_length=100)
    category = models.CharField(max_length=1, choices=INSTITUTE_CATEGORY)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    province_state = models.ForeignKey(ProvinceState, verbose_name='province/state')
    description = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'mva_institute'


class Specialization(models.Model):

    name = models.CharField(max_length=100, unique=True)
    user = models.ManyToManyField(User, through='SpecializationAssign')
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'mva_specialization'


class SpecializationAssign(models.Model):

    user = models.ForeignKey(User, related_name='%(class)s_user')
    specialization = models.ForeignKey(Specialization, related_name='%(class)s_specialization')

    def __unicode__(self):
        return '%s : %s' % (self.user, self.specialization)

    class Meta:
        db_table = 'mva_specialization_assign'
        verbose_name = 'specialization assignment'
        verbose_name_plural = 'specialization assignments'
        unique_together = ('user', 'specialization')


class Skill(models.Model):

    name = models.CharField(max_length=100, unique=True)
    user = models.ManyToManyField(User, through='SkillAssign')
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'mva_skill'


class SkillAssign(models.Model):

    user = models.ForeignKey(User, related_name='%(class)s_user')
    skill = models.ForeignKey(Skill, related_name='%(class)s_skill')
    rating = models.ManyToManyField(User, through='SkillRating')

    def __unicode__(self):
        return '%s : %s' % (self.user, self.skill)

    class Meta:
        db_table = 'mva_skill_assign'
        verbose_name = 'skill assignment'
        verbose_name_plural = 'skill assignments'
        unique_together = ('user', 'skill')


class SkillRating(models.Model):

    rater = models.ForeignKey(User, related_name='%(class)s_rater')
    skill_assign = models.ForeignKey(SkillAssign)
    value = models.PositiveIntegerField(default=0, choices=SKILL_RATING)

    def __unicode__(self):
        return '%s -> %s = %s' % (self.rater, self.skill_assign, self.value)

    class Meta:
        db_table = 'mva_skill_rating'
        verbose_name = 'skill rating'
        verbose_name_plural = 'skill ratings'
        unique_together = ('rater', 'skill_assign')


class Badge(models.Model):

    label = models.CharField(max_length=100)
    prev_lvl = models.OneToOneField('self', null=True, blank=True, related_name='%(class)s_prev_lvl', verbose_name='previous level')
    req_exp = models.PositiveIntegerField(default=0, verbose_name='requirement EXP')
    next_exp = models.PositiveIntegerField(default=0, verbose_name='next level EXP')
    next_lvl = models.OneToOneField('self', null=True, blank=True, related_name='%(class)s_next_lvl', verbose_name='next level')
    user = models.ManyToManyField(User, through='BadgeAssign')
    # picture = models.ImageField(null=True, blank=True)

    def __unicode__(self):
        return self.label

    class Meta:
        db_table = 'mva_badge'


class BadgeAssign(models.Model):

    user = models.ForeignKey(User, related_name='%(class)s_user')
    badge = models.ForeignKey(Badge, related_name='%(class)s_badge')
    obtained = models.BooleanField(default=False)
    exp = models.PositiveIntegerField(default=0, verbose_name='EXP')

    def __unicode__(self):
        return '%s : %s' % (self.user, self.badge)

    class Meta:
        db_table = 'mva_badge_assign'
        verbose_name = 'badge assignment'
        verbose_name_plural = 'badge assignments'
        unique_together = ('user', 'badge')


class Encouragement(SentContent):

    person_to = models.ForeignKey(User, related_name='%(class)s_person_to', verbose_name='to')
    approved = models.BooleanField(default=False)

    def __unicode__(self):
        return 'To %s: %s...' % (self.person_to, self.message[:10])

    def approve(self, approve=True):
        if approve:
            self.approved = approve
            self.save()
        else:
            self.delete()

    class Meta:
        db_table = 'mva_encouragement'


class Feedback(SentContent):

    instructor = models.ForeignKey(User)

    def __unicode__(self):
        return 'To %s: %s...' % (self.instructor, self.message[:10])

    class Meta:
        db_table = 'mva_feedback'


class WebFile(models.Model):

    name = models.CharField(max_length=100)
    item = models.FileField(upload_to='webfiles')
    uploader = models.ForeignKey(User, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'mva_webfile'
        verbose_name = 'web file'
        verbose_name_plural = 'web files'

course/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import Institute
from core.abstract_models import SentContent
from core.constants import (DURATION, COURSE_INTERESTING_RATING,
    COURSE_PRACTICAL_RATING, COURSE_DIFFICULT_RATING, SECTION_ROLE)


class Course(models.Model):

    title = models.CharField(max_length=100)
    abbrev = models.CharField(max_length=10, verbose_name='abbreviation', null=True, blank=True)
    institute = models.ForeignKey(Institute)
    description = models.TextField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s (%s)' % (self.title, self.abbrev)

    class Meta:
        db_table = 'mva_course'
        unique_together = ('title', 'abbrev', 'institute')


class CourseRating(models.Model):

    rater = models.ForeignKey(User, related_name='%(class)s_rater')
    course = models.ForeignKey(Course)
    interesting_value = models.PositiveIntegerField(default=0, choices=COURSE_INTERESTING_RATING)
    practical_value = models.PositiveIntegerField(default=0, choices=COURSE_PRACTICAL_RATING)
    difficult_value = models.PositiveIntegerField(default=0, choices=COURSE_DIFFICULT_RATING)

    def __unicode__(self):
        return '%s -> %s = %s, %s, %s' % (self.rater, self.course, self.interesting_value, self.practical_value, self.difficult_value)

    class Meta:
        db_table = 'mva_course_rating'
        verbose_name = 'course rating'
        verbose_name_plural = 'course ratings'
        unique_together = ('rater', 'course')


class Section(models.Model):

    course = models.ForeignKey(Course)
    start_date = models.DateField()
    duration = models.CharField(max_length=1, choices=DURATION, default='T')
    user = models.ManyToManyField(User, through='SectionAssign')

    def __unicode__(self):
        return '%s [%s, %s]' % (self.course, unicode(self.start_date), self.get_duration_display())

    class Meta:
        db_table = 'mva_section'
        unique_together = ('course', 'start_date', 'duration')


class SectionAssign(models.Model):

    user = models.ForeignKey(User, related_name='%(class)s_user')
    section = models.ForeignKey(Section, related_name='%(class)s_section')
    role = models.CharField(max_length=1, default='S', choices=SECTION_ROLE)

    def __unicode__(self):
        return '(%s | %s) : %s' % (self.user, self.section, self.role)

    class Meta:
        db_table = 'mva_section_assign'
        verbose_name = 'section assignment'
        verbose_name_plural = 'section assignments'
        unique_together = ('user', 'section')


class Review(SentContent):

    course = models.ForeignKey(Course)

    def __unicode__(self):
        return 'To %s: %s...' % (self.course, self.message[:10])

    class Meta:
        db_table = 'mva_review'


class WhiteboardPost(models.Model):

    section = models.ForeignKey(Section)
    author = models.ForeignKey(User)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s -> %s: %s' % (self.author, self.section, self.content[:10])

    class Meta:
        db_table = 'mva_whiteboard_post'


class WhiteboardComment(models.Model):

    post = models.ForeignKey(WhiteboardPost)
    author = models.ForeignKey(User)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s -> %s: %s' % (self.author, self.post.id, self.content[:10])

    class Meta:
        db_table = 'mva_whiteboard_comment'

crowd/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response
from crowd.forms import AddSpecializationForm, AddSkillForm, EncouragementForm
from account.models import Profile
from core.models import BadgeAssign, Encouragement


@login_required
def crowd(request, username=None):
    if username == None:
        user = request.user
    else:
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
    if user is not None:
        profile = user.get_profile()

        add_specialization_form = AddSpecializationForm(request=request)
        add_skill_form = AddSkillForm(request=request)
        encouragement_form = EncouragementForm(request=request)

        context = RequestContext(request)
        context['viewing_user'] = user
        context['profile'] = profile
        context['badges'] = BadgeAssign.objects.filter(user=user)
        context['encouragements'] = Encouragement.objects.filter(person_to=user).order_by('-sent_time')
        context['related'] = Profile.objects.filter(institute=profile.institute, role='S').exclude(id=request.user.profile.id).exclude(id=profile.id)
        context['add_specialization_form'] = add_specialization_form
        context['add_skill_form'] = add_skill_form
        context['encouragement_form'] = encouragement_form
        return render_to_response('crowd/main.html', context)
    else:
        return HttpResponse('User Not Found!')

schoolax/templates/crowd/main.html
{% extends "base.html" %}

{% load base_extra %}
{% load webdesign %}

{% block title %}{{ BRAND_NAME }} - Crowd{% endblock %}

{% block content %}

<div class="page-header">
  <div class="row-fluid">
    <div class="span1">
      <div class="thumbnail"><img src="http://placehold.it/100x100" alt="" />
      </div>
    </div>
    <div class="span11">
      <h1>{{ viewing_user.get_full_name }}</h1>
      {% if profile.degree %} <h6>{{ profile.get_degree_display }} {{ profile.get_role_display }} from {{ profile.institute }}</h6>
      {% else %} <h6>{{ profile.get_role_display }} from {{ profile.institute }}</h6>
      {% endif %} <div class="vertical-space"></div>
      <div class="row-fluid">
        <ul class="thumbnails">
          {% for b in badges %}
          <li>
            <a class="thumbnail" rel="popover" data-content="Obtained: {{ b.obtained }}<br />EXP: {{ b.exp }}<br />" data-original-title="{{ b.badge }}"> <img src="http://placehold.it/30x30" alt="" /> </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <div class="row-fluid">
      <h3>Schoolax Grade: <span id="grade-box">{{ profile.get_grade_display }}</span></h3>
      <h3>Gauge: <span id="exp-box">{{ profile.grade_gauge }}</span></h3>
      <div id="grade-gauge" class="progress">
        <div class="bar"></div>
      </div>
      {% if viewing_user == user %}
      <a class="btn btn-primary btn-mini" onclick="Dajaxice.crowd.plus_exp(update_exp);"> <i class="icon-plus icon-white"></i> EXP</a>
      <a class="btn btn-primary btn-mini" onclick="Dajaxice.crowd.minus_exp(update_exp);"> <i class="icon-minus icon-white"></i> EXP</a>
      {% endif %}
    </div>
    <div class="row-fluid">
      <div class="span6">  
        {% with specializations=viewing_user.specialization_set.all %} <h3>Specialization{{ specializations.count|pluralize }}:</h3>
        {% for specialization in specializations %} <h6>{{ specialization.name }}</h6>
        {% empty %} <h6>No Specialization Yet!</h6>
        {% endfor %}
        {% if viewing_user == user %} <div class="vertical-space"></div>
        <a data-toggle="modal" href="#add-specialization" class="btn btn-mini btn-info"><i class="icon-plus icon-white"></i> Specialization </a>
        {% endif %}
        {% endwith %}
      </div>
      <div class="span6">
        {% with skills=viewing_user.skill_set.all %} <h3>Skill{{ skills.count|pluralize }}:</h3>
        {% for skill in skills %} <h6>{{ skill.name }}</h6>
        {% empty %} <h6>No Skill Yet!</h6>
        {% endfor %}
        {% if viewing_user == user %} <div class="vertical-space"></div>
        <a data-toggle="modal" href="#add-skill" class="btn btn-mini btn-info"><i class="icon-plus icon-white"></i> Skill </a>
        {% endif %}
        {% endwith %}
      </div>
    </div>
    <div class="vertical-space"></div>
    <div class="row-fluid">
      {% if profile.role = 'S' %} <h3>Encouragement{{ encouragements.count|pluralize }}:</h3>
      <div class="vertical-space"></div>
      {% if viewing_user != user %} <div class="vertical-space"></div>
      <a data-toggle="modal" href="#encouragement" class="btn btn-mini btn-warning"><i class="icon-pencil icon-white"></i> Encouragement </a>
      <div class="vertical-space"></div>
      <div class="vertical-space"></div>
      {% endif %}
      {% for encouragement in encouragements %}
      <blockquote>
        <h6>{{ encouragement.sent_time }}</h6>
        <p>
          <i>"{{ encouragement.message }}"</i>
        </p><small>{% if encouragement.anonymous %} Anonymous {% else %} <a href="{% url crowd %}{{ encouragement.person_from.user.username }}">{{ encouragement.person_from.get_full_name }}</a>{% endif %}</small>
      </blockquote>
      {% empty %} <h6>No Encouragement Yet!</h6>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="span6">
    <div class="row-fluid">
      <form class="form-search">
        <input type="text" class="input-large">
        <button type="submit" class="btn">
          Search Anyone
        </button>
      </form>
      <h3>Related:</h3>
      <div class="vertical-space"></div>
      {% for p in related %}
      <div class="well">
        <h5><a href="{% url crowd %}{{ p.user.username }}">{{ p }}</a></h5>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    function update_exp(data) {
      $('#grade-box').html(data.grade);
      $('#exp-box').html(data.exp);
      render_gauge(data.exp);
    }
    
    function render_gauge(value) {
      var percentage = (value + 100) / 2;
      $('#grade-gauge .bar').attr('style', 'width: ' + percentage + '%');
      $('#grade-gauge').removeClass('progress-success');
      $('#grade-gauge').removeClass('progress-error');
      $('#grade-gauge').removeClass('progress-warning');
      if(percentage >= 66) {
          $('#grade-gauge').addClass('progress-success');
      }
      else if(percentage <= 33) {
          $('#grade-gauge').addClass('progress-danger');
      }
      else {
          $('#grade-gauge').addClass('progress-warning');
      }
    }

    $(document).ready(function() {
      render_gauge({{ profile.grade_gauge }});
    });
</script>

{% include "modal/add-specialization.html" %}
{% include "modal/add-skill.html" %}
{% include "modal/encouragement.html" %}

{% endblock %} 