backstage/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('backstage.views',
    url(r'^backstage/tickets/$', 'tickets', name='backstage_tickets'),
    url(r'^backstage/tickets_create/$', 'tickets_create'),
    url(r'^backstage/tickets/(?P<ticket_id>\d+)/$', 'tickets'),
    url(r'^backstage/wiki/$', 'wiki', name='backstage_wiki'),
    url(r'^backstage/wiki/(?P<wiki_id>\d+)/$', 'wiki'),
    url(r'^backstage/wiki_edit/$', 'wiki_edit'),
    url(r'^backstage/wiki_edit/(?P<wiki_id>\d+)/$', 'wiki_edit'),
    url(r'^backstage/dashboard/$', 'dashboard', name='backstage_dashboard'),
    url(r'^backstage/$', 'dashboard', name='backstage'),
    url(r'^onerror/$', 'onerror'),
)

data/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('data.views',
    url(r'^autocomplete_course/', 'autocomplete_course'),
    url(r'^autocomplete_specialization/', 'autocomplete_specialization'),
    url(r'^autocomplete_skill/', 'autocomplete_skill'),
)

schoolax/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover


admin.autodiscover()
dajaxice_autodiscover()

handler403 = 'core.views.error_403'
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'views.home', name='home'),
    # url(r'^Minerva/', include('foo.urls')),
    # Import URLs
    url(r'', include('bulletin.urls')),
    url(r'', include('account.urls')),
    url(r'', include('homeroom.urls')),
    url(r'', include('course.urls')),
    url(r'', include('portfolio.urls')),
    url(r'', include('backstage.urls')),
    url(r'', include('data.urls')),
    # Admin URLs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # AJAX URLs
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls'))
)

# Static File URLs
urlpatterns += staticfiles_urlpatterns()

backstage/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import WebFile
from core.constants import (TICKET_PRIORITY, TICKET_CATEGORY,
    TICKET_STATUS, LOG_LEVEL)
from datetime import datetime


class Ticket(models.Model):

    summary = models.CharField(max_length=100)
    reporter = models.ForeignKey(User, related_name='%(class)s_reporter', null=True, blank=True)
    owner = models.ForeignKey(User, related_name='%(class)s_owner', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=TICKET_STATUS, default='L')
    priority = models.PositiveIntegerField(choices=TICKET_PRIORITY, null=True, blank=True)
    category = models.CharField(max_length=1, choices=TICKET_CATEGORY, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s...' % self.summary[:10]

    class Meta:
        db_table = 'bsg_ticket'


class Wiki(models.Model):

    title = models.CharField(max_length=100)
    document = models.TextField()
    attachment = models.ManyToManyField(WebFile, through='WikiAttachmentAssign')
    author = models.ForeignKey(User, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def save(self, user=None, *args, **kwargs):
        try:
            old_version = Wiki.objects.get(id=self.id)
        except Wiki.DoesNotExist:
            old_version = None
        super(Wiki, self).save(*args, **kwargs)
        if old_version is not None and (self.document != old_version.document or self.title != old_version.title):
            revision_history = WikiRevisionHistory()
            revision_history.wiki = self
            revision_history.title_from = old_version.title
            revision_history.title_to = self.title
            revision_history.document_from = old_version.document
            revision_history.document_to = self.document
            revision_history.modified_by = user
            revision_history.save()

    class Meta:
        db_table = 'bsg_wiki'
        verbose_name_plural = 'wiki'


class WikiRevisionHistory(models.Model):

    wiki = models.ForeignKey(Wiki)
    title_from = models.CharField(max_length=100)
    title_to = models.CharField(max_length=100)
    document_from = models.TextField()
    document_to = models.TextField()
    modified_by = models.ForeignKey(User, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s: %s' % (self.wiki, unicode(self.created_time))

    class Meta:
        db_table = 'bsg_wiki_revision_history'
        verbose_name = 'wiki revision history'
        verbose_name_plural = 'wiki revision histories'


class WikiAttachmentAssign(models.Model):

    wiki = models.ForeignKey(Wiki)
    attachment = models.ForeignKey(WebFile)
    uploader = models.ForeignKey(User)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s : %s' % (self.wiki, self.attachment)

    class Meta:
        db_table = 'bsg_wiki_attachment_assign'
        verbose_name = 'wiki attachment assignment'
        verbose_name_plural = 'wiki attachment assignments'
        unique_together = ('wiki', 'attachment')


class LogMessage(models.Model):

    logger_name = models.CharField(max_length=100, blank=True, null=True)
    logged_time = models.DateTimeField(default=datetime.now())
    level = models.IntegerField(choices=LOG_LEVEL, blank=True, null=True)
    file_path = models.CharField(max_length=255, blank=True, null=True)
    function_name = models.CharField(max_length=255, blank=True, null=True)
    line_number = models.PositiveIntegerField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    traceback = models.TextField(blank=True, null=True)
    uri_path = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    request = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return '%s[%s] - %s' % (self.logger_name, self.get_level_display(), unicode(self.logged_time))

    class Meta:
        db_table = 'bsg_log_message'
        verbose_name = 'log message'
        verbose_name_plural = 'log messages'
        ordering = ['-logged_time']

backstage/forms.py
from django import forms
from core.forms import StandardForm, StandardModelForm
from backstage.models import Ticket


class ReportForm(StandardForm):

    message = forms.CharField(label='Please Write Your Report Below...', widget=forms.Textarea(attrs={'style': 'width:98%;resize:vertical'}))

    def clean_message(self):
        message = self.cleaned_data['message'].strip()
        return message


class TicketForm(StandardModelForm):

    class Meta:
        model = Ticket


class WikiForm(StandardForm):

    title = forms.CharField(label='Title')
    document = forms.CharField(label='Document', widget=forms.Textarea(attrs={'style': 'width:98%;resize:vertical'}))

    def clean_title(self):
        title = self.cleaned_data['title'].strip()
        return title

    def clean_document(self):
        document = self.cleaned_data['document'].strip()
        return document

backstage/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.template import RequestContext
from backstage.models import (Ticket, Wiki, WikiRevisionHistory,
    LogMessage)
from backstage.forms import TicketForm, WikiForm
from core.decorators import staff_required
from creoleparser import text2html
from datetime import datetime
import logging


@login_required
@staff_required
def dashboard(request):
    context = RequestContext(request)
    return render_to_response('backstage/dashboard.html', context)


@login_required
@staff_required
def tickets(request, ticket_id=None):
    context = RequestContext(request)
    if ticket_id is None:
        ticket_list = Ticket.objects.all()
        context['tickets'] = ticket_list
        return render_to_response('backstage/tickets.html', context)
    else:
        try:
            ticket = Ticket.objects.get(id=ticket_id)
        except Ticket.DoesNotExist:
            ticket = None
        if ticket is not None:
            if request.method == 'POST':
                form = TicketForm(request.POST, instance=ticket)
                if form.is_valid():
                    form.save()
            else:
                form = TicketForm(instance=ticket)
            context['ticket'] = ticket
            context['form'] = form
            return render_to_response('backstage/tickets_detail.html', context)
        else:
            return HttpResponse('Ticket Not Found!')


@login_required
@staff_required
def tickets_create(request, ticket_id=None):
    context = RequestContext(request)
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            form.save()
            return render_to_response('backstage/ticket_create_success.html', context)
    else:
        form = TicketForm()
    context['form'] = form
    return render_to_response('backstage/tickets_create.html', context)


@login_required
@staff_required
def wiki(request, wiki_id=None):
    context = RequestContext(request)
    if wiki_id is None:
        wiki_list = Wiki.objects.all()
        context['wikis'] = wiki_list
        return render_to_response('backstage/wiki.html', context)
    else:
        try:
            wiki_obj = Wiki.objects.get(id=wiki_id)
        except Wiki.DoesNotExist:
            wiki_obj = None
        if wiki_obj is not None:
            context['wiki'] = wiki_obj
            context['parsed'] = text2html(wiki_obj.document)
            context['revisions'] = WikiRevisionHistory.objects.filter(wiki=wiki_obj).order_by('-created_time')
            return render_to_response('backstage/wiki_detail.html', context)
        else:
            return HttpResponse('Wiki Not Found!')


@login_required
@staff_required
def wiki_edit(request, wiki_id=None):
    context = RequestContext(request)
    if request.method == 'POST':
        form = WikiForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = request.user
            try:
                wiki_obj = Wiki.objects.get(id=wiki_id)
            except Wiki.DoesNotExist:
                wiki_obj = Wiki()
                wiki_obj.author = user
            wiki_obj.title = data['title']
            wiki_obj.document = data['document']
            wiki_obj.save(user=user)
            return redirect('/backstage/wiki/%s' % wiki_obj.id)
    else:
        edit = False
        try:
            wiki_obj = Wiki.objects.get(id=wiki_id)
            form = WikiForm({'title': wiki_obj.title, 'document': wiki_obj.document})
            edit = True
        except Wiki.DoesNotExist:
            form = WikiForm()
        context['edit'] = edit
    context['form'] = form
    return render_to_response('backstage/wiki_edit.html', context)


@csrf_exempt
def onerror(request):
    if request.method != 'POST':
        ret = HttpResponse(content='POST Only', status=400)
    else:
        message = request.POST['message']
        line_number = request.POST['line_number']
        url = request.POST['url']
        log_message = LogMessage()
        log_message.logged_time = datetime.now()
        log_message.logger_name = 'client'
        log_message.level = logging.ERROR
        log_message.line_number = line_number
        log_message.message = message
        log_message.uri_path = url
        log_message.request = request
        if request.user.is_authenticated():
            log_message.user = request.user
        log_message.save()
        ret = HttpResponse(content='Success', status=201)
    return ret

schoolax/templates/backstage/dashboard.html
{% extends "base.html" %}

{% load base_extra %}
{% load webdesign %}

{% block title %}{{ SITE_NAME }} - Dashboard{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Dashboard</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    {% include "backstage/sidebar.html" %}
  </div>
  <div class="span9">
    <p>Contents Pending...</p>
  </div>
</div>

{% endblock %}

schoolax/templates/backstage/sidebar.html
{% load base_extra %}

<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">
      Backstage
    </li>
    <li class="{% active request '^(/backstage/|/backstage/dashboard.*)$' %}">
      <a href="{% url backstage_dashboard %}"><i class="icon-home"></i> Dashboard</a>
    </li>
    <li class="{% active request '^/backstage/tickets.*$' %}">
      <a href="{% url backstage_tickets %}"><i class="icon-tag"></i> Tickets</a>
    </li>
    <li class="{% active request '^/backstage/wiki.*$' %}">
      <a href="{% url backstage_wiki %}"><i class="icon-file"></i> Wiki</a>
    </li>
    <li>
      <a href="/admin/" target="_blank"><i class="icon-th-list"></i> Admin</a>
    </li>
  </ul>
</div>

schoolax/templates/backstage/ticket_create_success.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Tickets{% endblock %}

{% block content %}
<div class="page-header">
	<h1>Success!</h1>
</div>
<div class="row-fluid">
	<div class="span3">
		{% include "backstage/sidebar.html" %}
	</div>
	<div class="span9">
		<div class="alert alert-success">Thank you! Your ticket has been created!</div>
		<a class="btn" href="/backstage/tickets/">Back</a>
	</div>
</div>
{% endblock %} 

schoolax/templates/backstage/tickets.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Tickets{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Tickets</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    {% include "backstage/sidebar.html" %}
  </div>
  <div class="span9">
  	<a class="btn btn-primary" href="/backstage/tickets_create/">Add Ticket!</a>
  	<div class="vertical-space"></div> 
    <table id="datatable-ticket" class="table table-bordered">
      <thead>
        <tr>
          <th>Ticket</th>
          <th>Priority</th>
          <th>Category</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
      	{% for t in tickets %}
        <tr>
          <td><a href="{% url backstage_tickets %}{{ t.id }}"> #{{ t.id }} - {{ t.summary }}</a></td>
          <td><span class="label label-{{ t.get_priority_display|lower }}">{{ t.get_priority_display|upper }}</span></td>
          <td><span class="label label-{{ t.get_category_display|lower }}">{{ t.get_category_display|upper }}</span></td>
          <td><span class="label label-{{ t.get_status_display|lower }}">{{ t.get_status_display|upper }}</span></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	/* Table initialisation */
	$('#datatable-ticket').dataTable( {
		"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
		"sPaginationType": "bootstrap",
		"oLanguage": {
			"sLengthMenu": "_MENU_ tickets per page",
			"sEmptyTable": 'No tickets...',
			"sInfo": "Showing _START_ to _END_ of _TOTAL_ tickets",
			"sInfoEmpty": "Showing 0 to 0 of 0 tickets",
			"sInfoFiltered": "(filtered from _MAX_ total tickets)",
			"sZeroRecords": "No matching tickets...",
		},
		'bLengthChange': false,
		'bFilter': false,
		'iDisplayLength': 10,
	});
});
</script>

{% endblock %}

schoolax/templates/backstage/tickets_create.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Tickets{% endblock %}

{% block content %}
<div class="page-header">
	<h1>Create Ticket</h1>
</div>
<div class="row-fluid">
	<div class="span3">
		{% include "backstage/sidebar.html" %}
	</div>
	<div class="span9">
		<form action="" method="post" class="form-horizontal">
			{% csrf_token %}
			{{ form.as_standard }}
			{% if form.non_field_errors %}
			<div class="alert alert-error">
				{{ form.non_field_errors|safe }}
			</div>
			{% endif %}
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">
					Save
				</button>
				<button type="reset" class="btn">
					Cancel
				</button>
			</div>
		</form>
	</div>
</div>
{% endblock %} 

schoolax/templates/backstage/tickets_detail.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Tickets{% endblock %}

{% block content %}
<div class="page-header">
	<h1>#{{ ticket.id }} - {{ ticket.summary }}</h1>
</div>
<div class="row-fluid">
	<div class="span3">
		{% include "backstage/sidebar.html" %}
	</div>
	<div class="span9">
		<form action="" method="post" class="form-horizontal">
			{% csrf_token %}
			{{ form.as_standard }}
			{% if form.non_field_errors %}
			<div class="alert alert-error">
				{{ form.non_field_errors|safe }}
			</div>
			{% endif %}
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">
					Save
				</button>
				<button type="reset" class="btn">
					Cancel
				</button>
			</div>
		</form>
	</div>
</div>
{% endblock %} 

schoolax/templates/backstage/wiki.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Wiki{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Wiki</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    {% include "backstage/sidebar.html" %}
  </div>
  <div class="span9">
    <a href="/backstage/wiki_edit" class="btn btn-primary btn-small">Create</a>
    <div class="vertical-space"></div><div class="vertical-space"></div>
    {% for w in wikis %}
    <div class="well well-small">
      <a href="{% url backstage_wiki %}{{ w.id }}"> {{ w.title }}</a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

schoolax/templates/backstage/wiki_detail.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Wiki{% endblock %}

{% block content %}

<div class="row-fluid">
  <div class="span3">
    {% include "backstage/sidebar.html" %}
    <h4>Revisions: </h4>
    <ul>
    {% for revision in revisions %}
    <li><a href="#" class="wiki-revision" data-message="{{ revision.title_from }}<br /><br /><textarea>{{ revision.document_from }}</textarea>">{{ revision.created_time }} by {% if revision.modified_by %}{{ revision.modified_by.get_full_name }}{% else %}Unknown{% endif %}</a></li>
    {% endfor %}
    </ul>
  </div>
  <div class="span9">
    <div class="page-header">
      <h1>{{ wiki.title }}</h1>
      <div class="vertical-space"></div>
      <h5>Author: {% if wiki.author %}{{ wiki.author.get_full_name }}{% else %}Unknown{% endif %}</h5>
      <div class="vertical-space"></div>
      <a href="/backstage/wiki_edit/{{ wiki.id }}" class="btn btn-primary btn-mini">Edit</a>
    </div>
    {{ parsed|safe }}
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('a.wiki-revision').click(function() {
      var elem = $(this);
      message_modal({
        heading : 'Revision',
        message : elem.attr('data-message'),
      });
    });
  });
</script>

{% endblock %} 

schoolax/templates/backstage/wiki_edit.html
{% extends "base.html" %}

{% load base_extra %}

{% block title %}{{ SITE_NAME }} - Wiki{% endblock %}

{% block content %}

<div class="page-header">
  <h1>{{ edit|yesno:"Edit,Create,Create" }} Wiki</h1>
</div>
<div class="row-fluid">
  <div class="span3">
    {% include "backstage/sidebar.html" %}
  </div>
  <div class="span9">
    <form action="" method="post" class="form-horizontal">
      {% csrf_token %}
      {{ form.as_standard }}
      {% if form.non_field_errors %}
      <div class="alert alert-error">
        {{ form.non_field_errors|safe }}
      </div>
      {% endif %}
      <div class="form-actions">
        <button type="submit" class="btn btn-primary">
          Save
        </button>
        <button type="reset" class="btn">
          Cancel
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %} 